#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
_WORKTREE="$(basename "${PROJECT_ROOT}")"
_SETTINGS_FILE="${SCRIPT_DIR}/settings.${_WORKTREE}.txt"
[[ -f "${_SETTINGS_FILE}" ]] || { echo "ERROR: settings file not found: ${_SETTINGS_FILE}" >&2; exit 1; }
source "${_SETTINGS_FILE}"

FRONTEND_ENV="${PROJECT_ROOT}/${FRONTEND_DIR}/.env"

cat > "${FRONTEND_ENV}" <<EOF
# Auto-generated by generate-env.sh — do not edit manually
VITE_API_BASE_URL=${API_BASE_URL}
VITE_ADMIN_URL=${ADMIN_URL}
VITE_BACKEND_PORT=${BACKEND_PORT}
VITE_FRONTEND_PORT=${FRONTEND_PORT}
VITE_ENV=${ENV}
VITE_OTP_DEV_MODE=${OTP_DEV_MODE}
VITE_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY:-}
VITE_APP_VERSION=v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_BUILD_NUMBER}
EOF

echo "Wrote ${FRONTEND_ENV}"
