#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
_WORKTREE="$(basename "${PROJECT_ROOT}")"
_SETTINGS_FILE="${SCRIPT_DIR}/settings.${_WORKTREE}.txt"
[[ -f "${_SETTINGS_FILE}" ]] || { echo "ERROR: settings file not found: ${_SETTINGS_FILE}" >&2; exit 1; }
source "${_SETTINGS_FILE}"

FRONTEND_ENV="${PROJECT_ROOT}/${FRONTEND_DIR}/.env"

# Preserve non-VITE_ lines (Shopify PUBLIC_* / PRIVATE_* credentials etc.)
# Only update the VITE_* block so credentials aren't wiped on every run.
_PRESERVED=""
if [[ -f "${FRONTEND_ENV}" ]]; then
  _PRESERVED=$(grep -v '^VITE_' "${FRONTEND_ENV}" | grep -v '^# Auto-generated' || true)
fi

cat > "${FRONTEND_ENV}" <<EOF
# VITE vars — auto-generated by generate-env.sh (do not edit this block manually)
VITE_API_BASE_URL=${API_BASE_URL}
VITE_ADMIN_URL=${ADMIN_URL}
VITE_BACKEND_PORT=${BACKEND_PORT}
VITE_FRONTEND_PORT=${FRONTEND_PORT}
VITE_ENV=${ENV}
VITE_OTP_DEV_MODE=${OTP_DEV_MODE}
VITE_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY:-}
VITE_APP_VERSION=v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_BUILD_NUMBER}
EOF

# Re-append any preserved non-VITE_ content (Shopify credentials etc.)
if [[ -n "${_PRESERVED}" ]]; then
  echo "" >> "${FRONTEND_ENV}"
  echo "${_PRESERVED}" >> "${FRONTEND_ENV}"
fi

echo "Wrote ${FRONTEND_ENV} (preserved non-VITE_ lines)"
